---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: steam-rust-dedicated-data
spec:
  storageClassName: local-path-fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
