---
apiVersion: v1
kind: Service
metadata:
  name: steam-rust-dedicated-game-external
spec:
  selector:
    app: steam-rust-dedicated
  type: LoadBalancer
  ports:
    - name: game
      protocol: UDP
      port: 28015
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: steam-rust-dedicated-rcon-external
spec:
  selector:
    app: steam-rust-dedicated
  type: LoadBalancer
  ports:
    - name: rcon
      protocol: TCP
      port: 28016
      nodePort: 30001
